# Generated by Django 4.2.7 on 2024-04-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0005_user_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
