# Generated by Django 4.2.7 on 2023-11-22 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
        ('autho', '0008_alter_user_primary_role_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='permission.role'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=377005, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 58, 18, 939147, tzinfo=datetime.timezone.utc)),
        ),
    ]
