# Generated by Django 4.2.7 on 2023-11-25 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
        ('autho', '0009_alter_user_roles_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='permission.role'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=852659, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 4, 7, 47, 459866, tzinfo=datetime.timezone.utc)),
        ),
    ]
