# Generated by Django 4.2.7 on 2023-11-25 06:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0013_alter_ratingandreview_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandreview',
            name='review',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be between 1 and 5.'), django.core.validators.MaxValueValidator(5, message='Rating must be between 1 and 5.')]),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=710892, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 6, 51, 44, 775711, tzinfo=datetime.timezone.utc)),
        ),
    ]
