# Generated by Django 4.2.7 on 2023-11-25 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0022_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicattribute',
            name='mechanic_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=975222, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 31, 15, 523873, tzinfo=datetime.timezone.utc)),
        ),
    ]
