# Generated by Django 4.2.7 on 2023-11-26 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_repair', '0006_alter_vehiclerepairrequestimage_image_and_more'),
        ('autho', '0023_mechanicattribute_mechanic_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MechanicAttribute',
            new_name='MechanicProfile',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=596347, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 5, 39, 5, 842083, tzinfo=datetime.timezone.utc)),
        ),
    ]
