# Generated by Django 4.2.7 on 2023-12-06 18:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0028_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicprofile',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mechanicprofile',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='ratingandreview',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ratingandreview',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='verificationcode',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='userblacklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userblacklist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=136185, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 18, 38, 2, 240367, tzinfo=datetime.timezone.utc)),
        ),
    ]
