# Generated by Django 4.2.7 on 2023-12-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0029_rename_created_on_mechanicprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=261745, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 18, 40, 38, 935496, tzinfo=datetime.timezone.utc)),
        ),
    ]
