# Generated by Django 4.2.7 on 2023-12-08 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0030_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=208935, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 19, 1, 544111, tzinfo=datetime.timezone.utc)),
        ),
    ]
