# Generated by Django 4.2.7 on 2023-12-08 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0031_user_additional_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_attributes',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=857173, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 21, 16, 394379, tzinfo=datetime.timezone.utc)),
        ),
    ]
