# Generated by Django 4.2.7 on 2023-12-10 01:06

import autho.models.verification_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0033_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=585867, max_length=6),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_on',
            field=models.DateTimeField(default=autho.models.verification_code.get_otp_expires_on),
        ),
    ]
