# Generated by Django 4.2.7 on 2023-12-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0034_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=645993, max_length=6),
        ),
    ]
