# Generated by Django 4.2.7 on 2023-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0035_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=570554, max_length=6),
        ),
    ]
