# Generated by Django 4.2.7 on 2023-12-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0037_alter_verificationcode_code_mechanictip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=584509, max_length=6),
        ),
    ]
