# Generated by Django 4.2.7 on 2023-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0047_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=139776, max_length=6),
        ),
    ]
