# Generated by Django 4.2.7 on 2023-12-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0050_alter_ratingandreview_repair_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=411188, max_length=6),
        ),
    ]
