# Generated by Django 4.2.7 on 2023-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0053_alter_userlocation_user_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=529481, max_length=6),
        ),
    ]
