# Generated by Django 4.2.7 on 2023-12-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0054_alter_user_additional_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_mobile_verified',
            new_name='is_phone_verified',
        ),
        migrations.RenameField(
            model_name='userblacklist',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=775123, max_length=6),
        ),
    ]
