# Generated by Django 4.2.7 on 2024-01-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_repair', '0014_vehiclerepairrequest_location'),
        ('autho', '0057_alter_verificationcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='vehicle_part_speciality',
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='service_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_repair.service'),
        ),
    ]
