# Generated by Django 4.2.7 on 2023-11-15 10:43

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'unique_together': {('name', 'method')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='permission.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='permission.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
