# Generated by Django 4.2.7 on 2023-11-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_alter_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
