# Generated by Django 4.2.7 on 2023-12-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_alter_permission_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='modified_on',
            new_name='modified_at',
        ),
    ]
