# Generated by Django 4.2.7 on 2024-03-24 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_obsolete", models.BooleanField(db_index=True, default=False)),
                ("code", models.CharField(max_length=6)),
                ("token", models.CharField(max_length=64, null=True)),
                ("expired_on", models.DateTimeField(null=True)),
                ("locked_at", models.DateTimeField(null=True)),
                ("retries", models.PositiveSmallIntegerField(default=0)),
                ("sents", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="dob_type",
            field=models.CharField(choices=[("bs", "Bs"), ("ad", "Ad")], default="ad", max_length=2),
        ),
        migrations.DeleteModel(
            name="MechanicTip",
        ),
        migrations.AddField(
            model_name="recoverycode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="recovery_code", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
