# Generated by Django 4.2.7 on 2024-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0002_recoverycode_alter_user_dob_type_delete_mechanictip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcode",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="expires_on",
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="tries",
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="expired_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="locked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="retries",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="sents",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="token",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
    ]
