# Generated by Django 4.2.7 on 2024-03-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0003_remove_verificationcode_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("bazra", "Bazra"), ("google", "Google"), ("facebook", "Facebook")],
                default="bazra",
                max_length=50,
            ),
        ),
    ]
