apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazra-deployment
  labels:
    app: bazra-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bazra-deployment
  template:
    metadata:
      labels:
        app: bazra-deployment
    spec:
      containers:
      - name: bazra-app
        image: registry.digitalocean.com/bazra/bazra-app:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: bazra-k8s-prod-env
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/secrets/firebase-credentials.json
        ports:
        - containerPort: 8000
        command: ["gunicorn", "-b", "0.0.0.0:8000", "bazra_dj.wsgi"]
        volumeMounts:
        - name: firebase-credentials-volume
          mountPath: /app/secrets/firebase-credentials.json
          subPath: firebase-credentials.json
        - name: static-files
          mountPath: /app/static

      - name: bazra-app-daphne
        image: registry.digitalocean.com/bazra/bazra-app:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: bazra-k8s-prod-env
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/secrets/firebase-credentials.json
        ports:
        - containerPort: 8001
        command: ["daphne", "-b", "0.0.0.0", "-p", "8001", "bazra_dj.asgi:application"]
        volumeMounts:
        - name: firebase-credentials-volume
          mountPath: /app/secrets/firebase-credentials.json
          subPath: firebase-credentials.json
        - name: static-files
          mountPath: /app/static

      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html/static
        - name: nginx-config
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: firebase-credentials-volume
        secret:
          secretName: firebase-credentials
      - name: static-files
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config

      imagePullSecrets:
      - name: bazra
---
apiVersion: v1
kind: Service
metadata:
  name: bazra-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8082
    # Here setting nginx container's port to 8082 instead of 80 and map service's container port to 80 instead of 8080, because
    # overv/openstreetmap-tile-server has hardcoded container to expose service on 80
  - name: map
    protocol: TCP
    port: 8080
    targetPort: 80 #(swith2 has hardcoded this port)
  - name: osrm
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: nominatim
    protocol: TCP
    port: 8090
    targetPort: 8080 #(nominatim has hardcoded this port)
  selector:
    app: bazra-deployment
