name: Bazra CI and Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  bazra_test:
    runs-on: ubuntu-latest

    services:
      postgres_main:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    env:
      DJANGO_SECRET_KEY: test-secret-key
      DB_HOST: localhost
      DB_NAME: bazra
      DB_USER: bazra
      DB_PASSWORD: bazra
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v3
      
      - name: Clear Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }} 

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test
